name = "my_hello_world"
description = "My First Program"
version = "0.1.0-dev"

authors = ["theTechyTaran"]
maintainers = ["theTechyTaran <68347504+booboojp@users.noreply.github.com>"]
maintainers-logins = ["booboojp"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []
